[hosts.mac-home]
host = "100.86.8.123"
user = "nishit.gupta"
desc = "MacBook via Tailscale"
mosh = true

[hosts.android]
host = "100.71.204.114"
user = "u0_a521"
port = 8022
desc = "Android via Tailscale"
mosh = false
